### ISSUE TITLE
【More hotkey setting】Will Path Finder add some hotkey setting for going to next/previous path result？

### ISSUE THREAD

**Issue by suliveevil** [jerrywcy/obsidian-path-finder#1]
**Is your feature request related to a problem? Please describe.**

The previous/next button is not fixed, it's better to use hotkey than mouse click.

**Describe the solution you'd like**

Will Path Finder add some hotkey setting for going to next/previous path result？

Thank you very much.

**Comment by jerrywcy** [comment]
Thanks for your suggestion! I haven't realized such a problem exist and will definitely add it to my todo list. 
I was busy preparing ACT the days before so I didn't do much coding, but now I have much free time so I will continue coding. 
Due to my limited ability, I cannot guarantee a perfect implementation, but I'll try my best.

**Comment by jerrywcy** [comment]
This feature is added in commit f1662709f0b18e8714b0c210ae437fbbe2095702.

**Comment by suliveevil** [comment]
It works like a charm!

**Comment by jerrywcy** [comment]
> It works like a charm!

Very glad you liked it! Please send an issue if you found any bugs when using :)
